git was working fine for me yesterday.
$ git push origin master
To github.com:fcastrow/06-Python-APIs_Homework.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:fcastrow/06-Python-APIs_Homework.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Fred@LAPTOP-9S9UDQCL MINGW64 ~/Desktop/06-Python-APIs/Homework/Instructions/06-Python-APIs_Homework (master)